---
name: "tagged-release"

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - '*'

jobs:
  tagged-release:
    name: tagged-release
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go 1.16
        uses: actions/setup-go@v3
        with:
          go-version: 1.16

      - name: Create Release Artifacts
        run: make create-release-artifacts

      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            release/*
